### ISSUE TITLE
 integrate MAZEBOT API 

### ISSUE THREAD

**Issue by mamonu** [mamonu/Astar#6]
Perhaps someone can help with integrating the github mazebot API? Ie get a maze from the api and solve it with the algorithm and return the solution through the API?

for some information on what the github MazebotAPI is have a look at:

https://github.com/mamonu/Astar/blob/master/MazebotAPI.md

**Comment by Fayhen** [comment]
Hi! I would be glad to help to try to integrate MazebotAPI requests in your code. First I need to know exactly what and where in your code you need data returned from the API.

My guess is that you could use a function that makes a request to MazebotAPI, which returns a `grid` variable containing the generated maze? Just like your current `randomgrid(mazesize)` function does locally, but returning the maze from MazebotAPI instead. Is that correct?

**Comment by mamonu** [comment]
yes. and it needs to be in a format that is like the output of randomgrid(mazesize) basically.

**Comment by Fayhen** [comment]
Got it working and shall be making a pull request shortly. I used Python's `requests` module (may require a quick install) and added a `requirements.txt` file, as well as a `.gitgnore`. I added three functions to `mazebotapi.py` , one which will request a maze of random size, another which will allow you to set the size of the requested maze, and one to parse the request data into a numpy array. The functions also return the start and goal coordinates, as they are set on the MazebotAPI request data.

There are just two considerations to be made:
- The Mazebot API documentation indicates 10, 20, 30, 40, 60, 100, 120, 150 and 200 as possible size values. By testing these requests, however, I figured that currently whenever you ask for a 30x30 maze you'll get a 404 response. You can verify this at: [https://api.noopschallenge.com/mazebot/random?minSize=30&maxSize=30](url). I have therefore removed this value from the list of valid integers on the input function.
- I tested the script with mazes of all sizes. It either works or returns a TypeError whose output I put just below. I don't have detailed knowledge on how these algorithms work, nor wanted to wrongly meddle on non API-related code. So, the cause is still to be investigated. The TypeError is:
`Traceback (most recent call last):
  File "\Astar\a_star.py", line 179, in <module>
    route = route + [start]
TypeError: unsupported operand type(s) for +: 'bool' and 'list'`

That being said, one can just rerun the script until it works, and can see it solving a 150x150 maze like:
[https://drive.google.com/file/d/1HkCeqj3ZEKiZW7efnypjlfnfbhpaSmi2/view?usp=sharing](url)
[https://drive.google.com/file/d/1reucjpvPtCuQOt9HZ5_JbLMFAglN9Bjw/view?usp=sharing](url)

**Comment by mamonu** [comment]
very good work. well done mate
